[project]
name = "konto-kompass-api"
version = "0.1.0"
dependencies = [
  "fastapi==0.115.8",
  "uvicorn[standard]==0.34.0",
  "SQLAlchemy==2.0.32",
  "psycopg[binary]==3.2.1",
  "pydantic==2.10.6",
]

[tool.setuptools.packages.find]
where = ["app"]
